# Generated by Django 5.1.6 on 2025-04-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedidos_semillas_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio',
        ),
    ]
