# Generated by Django 5.2.1 on 2025-05-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
