# Generated by Django 5.2.1 on 2025-05-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('num_bandejas', models.IntegerField()),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.group')),
            ],
        ),
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_bandejas', models.IntegerField()),
                ('id_invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernadero.invernadero')),
            ],
        ),
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_semilla', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('id_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernadero.racks')),
            ],
        ),
    ]
