# Generated by Django 5.2.1 on 2025-05-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeja',
            name='id_semilla',
        ),
    ]
