# Generated by Django 5.2.1 on 2025-05-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0002_remove_bandeja_id_semilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeja',
            name='disponible',
        ),
        migrations.AddField(
            model_name='bandeja',
            name='cantidad_riego',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bandeja',
            name='veces_riego',
            field=models.IntegerField(default=0),
        ),
    ]
