# Generated by Django 5.2.1 on 2025-05-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0003_remove_bandeja_disponible_bandeja_cantidad_riego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeja',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='bandeja',
            name='semilla',
            field=models.CharField(default='No hay semilla', max_length=100),
        ),
    ]
