# Generated by Django 5.2.1 on 2025-05-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0004_remove_bandeja_fecha_inicio_bandeja_semilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeja',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
