# Generated by Django 5.2.1 on 2025-05-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0005_bandeja_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeja',
            name='cantidad_riego',
        ),
        migrations.RemoveField(
            model_name='bandeja',
            name='veces_riego',
        ),
    ]
