# Generated by Django 5.2.1 on 2025-05-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0006_remove_bandeja_cantidad_riego_and_more'),
        ('pedidos', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeja',
            name='pedido_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.detallepedido'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='group_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.group'),
        ),
    ]
