# Generated by Django 5.2.1 on 2025-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0007_bandeja_pedido_id_alter_invernadero_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandeja',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
