# Generated by Django 5.2.1 on 2025-05-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invernadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('qos', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invernadero.invernadero')),
            ],
        ),
    ]
