# Generated by Django 5.2.1 on 2025-05-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='mqtt',
            name='qos',
        ),
    ]
